#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication blockMesh
cp 0/phi.orig 0/phi
cp 0/T.orig 0/T

runApplication setFields

runApplication decomposePar
# to run in cluster, use the job submission script
# to run in PC, run the below commands for serial/parallel execution
#to run serially
#runApplication allenCahnSolidification
#to run in parallel
#runApplication mpirun -np 4 allenCahnSolidification -parallel
#runApplication reconstructPar

#------------------------------------------------------------------------------
